### ISSUE TITLE
TFM Profesorado, nombres abreviados

### ISSUE THREAD

**Issue by unintendedbear** [unintendedbear/TFM#15]
¿Se os ocurre cómo hacer para que

```
@misc{datos::uni,
 author = {Ministerio de Educaci\'on, Cultura y Deporte. Gobierno de España.},
 title = {Datos y Cifras del Sistema Universitario espa\~{n}ol},
url = {http://www.mecd.gob.es/educacion-mecd/areas-educacion/universidades/estadisticas-informes/estadisticas/alumnado.html},
 year = {2004--2015},
}
```

no salga como

> MINISTERIO DE EDUCACIÓN, C. Y. D. G. d. E. Datos y Cifras del Sistema Universitario español. 2004-2015

(la parte C. Y. D. G. d. E. que queda horrible)?

¿Y que además salga la URL? :_
@fergunet @deantares @JJ @mgarenas @pacastillo :(

**Comment by JJ** [comment]
Pero ¿cómo lo has solucionado?

Yo lo pondría como "TechRep", usaría eso como institution y pondría los
verdaderos autores o "varios autores"
